# Generated by Django 5.0.6 on 2024-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subsystem Name', models.CharField(max_length=50)),
                ('Subsystem Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Robot Name', models.CharField(default='NewRobot', max_length=50)),
                ('FRC Year', models.IntegerField(default=2024, null=True)),
                ('Team Number', models.IntegerField(default=0, null=True)),
                ('DriveTrain Type', models.CharField(default='Tank Drive', max_length=50, null=True)),
                ('subsystems', models.ManyToManyField(blank=True, to='ConfigApp.subsystem')),
            ],
        ),
    ]
