# Generated by Django 5.0.6 on 2024-07-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0002_alter_subsystem_subsystem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='DriveTrain Type',
            field=models.CharField(blank=True, default='Tank Drive', max_length=50),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='FRC Year',
            field=models.IntegerField(blank=True, default=2024),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='Team Number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
