# Generated by Django 5.0.6 on 2024-07-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0003_alter_configuration_drivetrain_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='Robot Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
