# Generated by Django 5.0.6 on 2024-07-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0004_configuration_robot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Robot Name', models.CharField(default='NewRobot', max_length=50)),
                ('Robot Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('FRC Year', models.IntegerField(blank=True, default=2024)),
                ('Team Number', models.IntegerField(blank=True, default=0)),
                ('DriveTrain Type', models.CharField(blank=True, default='Tank Drive', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubsystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subsystem Configuration Name', models.CharField(max_length=50)),
                ('subsystems', models.ManyToManyField(blank=True, to='ConfigApp.subsystem')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_config', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ConfigApp.robotconfiguration')),
                ('subsystem_config', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ConfigApp.subsystemconfiguration')),
            ],
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
