# Generated by Django 5.0.6 on 2024-07-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0005_robotconfiguration_subsystemconfiguration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentconfiguration',
            name='robot_config',
        ),
        migrations.RemoveField(
            model_name='currentconfiguration',
            name='subsystem_config',
        ),
        migrations.RemoveField(
            model_name='subsystemconfiguration',
            name='subsystems',
        ),
        migrations.AddField(
            model_name='currentconfiguration',
            name='Robot Config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfigApp.robotconfiguration'),
        ),
        migrations.AddField(
            model_name='currentconfiguration',
            name='Subsystem Config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfigApp.subsystemconfiguration'),
        ),
        migrations.AddField(
            model_name='subsystemconfiguration',
            name='Subsystems',
            field=models.ManyToManyField(blank=True, to='ConfigApp.subsystem'),
        ),
    ]
