# Generated by Django 5.0.6 on 2024-07-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0006_remove_currentconfiguration_robot_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsystemconfiguration',
            old_name='Subsystem Configuration Name',
            new_name='SubConfigName',
        ),
    ]
