# Generated by Django 5.0.6 on 2024-07-29 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0007_rename_subsystem_configuration_name_subsystemconfiguration_subconfigname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentconfiguration',
            old_name='Robot Config',
            new_name='RobotConfig',
        ),
        migrations.RenameField(
            model_name='currentconfiguration',
            old_name='Subsystem Config',
            new_name='SubsystemConfig',
        ),
    ]
