# Generated by Django 5.0.6 on 2024-07-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0008_rename_robot_config_currentconfiguration_robotconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentconfiguration',
            name='CreatedBy',
            field=models.CharField(default='dmac', max_length=50),
        ),
    ]
