# Generated by Django 5.0.6 on 2024-07-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0009_currentconfiguration_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotconfiguration',
            name='CreatedBy',
            field=models.CharField(default='dmac', max_length=50),
        ),
    ]
