# Generated by Django 5.0.6 on 2024-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0011_subsystemconfiguration_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsystem',
            name='CreatedBy',
            field=models.CharField(default='dmac', max_length=50),
        ),
    ]
