# Generated by Django 5.0.6 on 2024-07-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0013_rename_drivetrain_type_robotconfiguration_drivetraintype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsystem',
            old_name='Subsystem Image',
            new_name='SubsystemImage',
        ),
        migrations.RenameField(
            model_name='subsystem',
            old_name='Subsystem Name',
            new_name='SubsystemName',
        ),
    ]
