# Generated by Django 5.0.6 on 2024-08-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfigApp', '0014_rename_subsystem_image_subsystem_subsystemimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotconfiguration',
            name='RobotImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='subsystem',
            name='SubsystemImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
