# Generated by Django 5.0.6 on 2024-08-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ConfigApp', '0015_alter_robotconfiguration_robotimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedBy', models.CharField(default='dmac', max_length=50)),
                ('CompName', models.CharField(blank=True, max_length=100)),
                ('MatchNumber', models.IntegerField(blank=True, default=0)),
                ('AnalyzeFile', models.FileField(blank=True, null=True, upload_to='datafiles/')),
                ('CurrentConfig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ConfigApp.currentconfiguration')),
            ],
        ),
    ]
