# Generated by Django 5.0.6 on 2024-08-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnalyzeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
